### ISSUE TITLE
Test data is in the training / dev set as well

### ISSUE THREAD

**Issue by PonteIneptique** [Heresta/datasetsOCRSegmenter17#1]
If I am not mistaken, you are checking for full path equivalency ( https://github.com/Heresta/OCR17plus/blob/11f57a5cddacae7ed42326f0070fbd4123b1b1ba/train_val_prep.py#L13 ) between a file starting with `./trainingDataSeg17` and their original path (`Data/{Bookname}/{Format}/file.xml`). This means a filepath passed to the argument probably is never seen in the `test.txt`

I think this should be checked but I have some doubts here.

**Comment by Heresta** [comment]
Thanks for your feedback. It has been modified.
